### ISSUE TITLE
: No such file or directory using ubuntu

### ISSUE THREAD

**Issue by rhalff** [mohebifar/xto6#3]
I've tried to use xto6 on ubuntu but the execution fails because the package on npm contains windows line breaks instead of unix.

```
$ npm i xto6 -g
$ xto6 test.js
: No such file or directory
```

```
$ cat -v /home/ubuntu/.nvm/v0.10.35/lib/node_modules/xto6/bin/index.js | head -n 3
#!/usr/bin/env node^M
var program = require('commander');^M
var fs = require("fs");^M
```

When I fix the line breaks xto6 executes correctly.
```
$ dos2unix  /home/ubuntu/.nvm/v0.10.35/lib/node_modules/xto6/bin/index.js
dos2unix: converting file /home/ubuntu/.nvm/v0.10.35/lib/node_modules/xto6/bin/index.js to Unix format ...
$ xto6 test.js                                                   
The file "output.js" has been written.
```

When I install from github directly using `npm i mohebifar/xto6 -g` there is no such problem,
so probably there is something going wrong during the publishing process to npm.

**Comment by mohebifar** [comment]
Thanks, fixed by republishing it on npm.
