### ISSUE TITLE
error in Safari, no `Symbol`

### ISSUE THREAD

**Issue by timoxley** [mohebifar/xto6#30]
Looks like you need to polyfill missing browser features in the website.

As [reported](https://twitter.com/ljharb/status/588199586205958144) by @ljharb

**Comment by timoxley** [comment]
![image](https://cloud.githubusercontent.com/assets/43438/7152406/fca72112-e36d-11e4-8e99-7672f7d1ed05.png)

**Comment by ljharb** [comment]
Thanks for taking care of the *real* report!

**Comment by mohebifar** [comment]
This is because babel's for..of transformed code requires `Symbol` which is not supported by Safari. I added babel polyfill in d93d979.

**Comment by ljharb** [comment]
Thanks!

**Comment by mohebifar** [comment]
Thank you for report.
