### ISSUE TITLE
Symbol is not defined

### ISSUE THREAD

**Issue by jaydson** [mohebifar/xto6#34]
I tried to run the very same website example:
```bash
xto6 person.js -o person-es6.js
```

Then i have the following error:
```
 throw _iteratorError;
                  ^
ReferenceError: Symbol is not defined

```

**Comment by mohebifar** [comment]
There might be some compatibility issue. Which version of node.js are you using ?

**Comment by jaydson** [comment]
`v0.11.14` but i'm using `nvm`, so i can easily change it.
Which version is required? `0.10`?

**Comment by jaydson** [comment]
Just tried with `0.10`. Same error.

**Comment by mdibaiee** [comment]
You should use `0.12`. The latest version is `0.12.2`

**Comment by mdibaiee** [comment]
Add symbols to release build

[0.12 changelog](https://raw.githubusercontent.com/joyent/node/v0.12.0/ChangeLog)

**Comment by jaydson** [comment]
Oh, i see. Thanks!
BTW, check the issue #35
