### ISSUE TITLE
Convert var to const/let

### ISSUE THREAD

**Issue by pornel** [mohebifar/xto6#6]
If a variable is only assigned to once, convert its declaration to `const`, otherwise `let` in the innermost block that covers all uses of a variable within the function.

**Comment by goatslacker** [comment]
@mohebifar I have a bunch of these features (let/const, modules, object concise) already semi-done, feel free to lift some code or ideas from here: https://github.com/goatslacker/sixit

feel free to also reach me via email (in my profile)
